# Generated by Django 4.0.1 on 2022-05-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_constituency', models.CharField(max_length=100, unique=True)),
                ('constituency_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('active', 'Active'), ('deactivate', 'Deactivate'), ('delete', 'Delete'), ('closed', 'Closed')], max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='district.district')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region', to='region.region')),
            ],
        ),
    ]
