# Generated by Django 4.0.1 on 2022-05-07 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constituency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_polling_station', models.CharField(max_length=100, unique=True)),
                ('polling_station_code', models.CharField(max_length=50, unique=True)),
                ('voters_population', models.IntegerField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('approved', 'Approved'), ('active', 'Active'), ('deactivate', 'Deactivate'), ('delete', 'Delete'), ('closed', 'Closed')], max_length=100)),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituency', to='constituency.constituency')),
            ],
        ),
    ]
